# permissions for end users to edit managedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: managed-secret-operator
    app.kubernetes.io/part-of: managed-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedsecret-editor-role
rules:
- apiGroups:
  - managed-secret.lib250.domain
  resources:
  - managedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-secret.lib250.domain
  resources:
  - managedsecrets/status
  verbs:
  - get
