apiVersion: managed-secret.lib250.domain/v1alpha1
kind: ManagedSecret
metadata:
  labels:
    app.kubernetes.io/name: managedsecret
    app.kubernetes.io/instance: managedsecret-sample
    app.kubernetes.io/part-of: managed-secret-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: managed-secret-operator
  name: managedsecret-sample
spec:
  # TODO(user): Add fields here
